# Generated by Django 2.1 on 2020-01-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20200106_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_likes',
            field=models.IntegerField(default=0),
        ),
    ]
