# Generated by Django 2.1 on 2020-01-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20200106_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
        ),
    ]
